---
title: "Week 9: Code along 8"
subtitle: "R for Data Science: Chapter 13"
author: "Daniel Lee"
date: "2022-10-05"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Load package
library(tidyverse)
library(nycflights13)
```

## Introduction

## nycflights13

## Keys

## Mutating joins

### Inner join
```{r}
x <- tribble(
  ~key, ~val_x,
     1, "x1",
     2, "x2",
     3, "x3"
)
y <- tribble(
  ~key, ~val_y,
     1, "y1",
     2, "y2",
     4, "y3"
)

inner_join(x, y)
```

### Outer joins
```{r}
left_join(x, y)
right_join(x, y)
full_join(x, y)
```

### Defining the key columns
```{r}
flights %>% left_join(planes)
flights %>% left_join(planes, by = "tailnum")
```

## Filtering joins

```{r}
semi_join(x, y)
semi_join(y, x)
anti_join(x, y)
anti_join(y, x)
```

## Join problems

```{r}
airports %>% count(lat, lon) %>% arrange(desc(n))
left_join(x, y)
```


## Set operations

```{r}
df1 <- tribble(
  ~x, ~y,
   1,  1,
   2,  1
)
df2 <- tribble(
  ~x, ~y,
   1,  1,
   1,  2
)
```

```{r}
intersect(df1, df2)
union(df1, df2)
setdiff(df1, df2)
setdiff(df2, df1)
```


